spring:
  application:
    name: labstore

  datasource:
    url: jdbc:postgresql://localhost:5432/labstore
    driverClassName: org.postgresql.Driver
    username: postgres
    password: 1

  jpa:
    hibernate:
      ddl-auto: none

  flyway:
    enabled: true

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
server:
  port: 60006